PREFIX=/usr/local/mapd-deps
LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$PREFIX/lib64:$LD_LIBRARY_PATH
PATH=/usr/local/cuda/bin:$PATH
PATH=$PREFIX/bin:$PATH
VULKAN_SDK=$PREFIX
VK_LAYER_PATH=$PREFIX/etc/vulkan/explicit_layer.d
CMAKE_PREFIX_PATH=$PREFIX:$CMAKE_PREFIX_PATH
export LD_LIBRARY_PATH PATH VULKAN_SDK VK_LAYER_PATH CMAKE_PREFIX_PATH
